on:
  push:
    branches:
      - main
    paths:
    - ".github/workflows/pycontw2023.yml"
    - "talks/pycontw2023/**"

env:
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read

    outputs:
      status: ${{ job.status }}
    env:
      AWS_REGION: ap-northeast-1
      AWS_ROLE_ARN: arn:aws:iam::981709652793:role/PipelineUploadS3
      S3_BUCKET: slides.peacock0803sz.com

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials From Web Identity
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18'

      - name: Build and deploy to s3 bucket
        env:
          S3_REPOSITORY: s3://${{ env.S3_BUCKET }}
        run: |
          pnpm install
          cd talks/pycontw2023
          mkdir -p ./dist/
          pnpm run build:aws
          pnpm run render:cover
          aws s3 sync ./dist $S3_REPOSITORY/pycontw2023/
