on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/theme-watercolors.yml"
      - "themes/watercolors/**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: "9.6"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF

      - uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cwd: themes/watercolors
          publish: pnpm publish --no-git-checks
